name: Send Random Note

on:
  schedule:
    - cron: '30 5,8,11,14,17,20 * * *'  # UTC ile: 08:30, 11:30, 14:30, 17:30, 20:30, 23:30 Türkiye saati
  workflow_dispatch:  # Manuel başlatma opsiyonu

jobs:
  send-note:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python main.py
